name: ExtDN Actions
on: [push, pull_request]

jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard@master

  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: M2 Unit Tests with Magento 2.3.5
        uses: extdn/github-actions-m2/magento-unit-tests@master
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            MODULE_NAME: ${{ secrets.MODULE_NAME }}
            COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
            CE_VERSION: 2.3.5

  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests
        uses: extdn/github-actions-m2/magento-integration-tests@master
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            MODULE_NAME: ${{ secrets.MODULE_NAME }}
            COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
            CE_VERSION: 2.3.5

