name: ExtDN Static Tests
on: [push]

jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-coding-standard/8.3@master
        with:
          phpcs_severity: 8
          phpcs_report: full
          phpcs_extensions: php
