name: ExtDN Unit Tests
on: [push]

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    env:
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: extdn/github-actions-m2/magento-unit-tests/8.3@master
        env:
          MAGENTO_VERSION: '2.4.7'
          COMPOSER_VERSION: 2